#! /bin/sh

clean=0

while getopts crdph name
do
	case $name in
	c) clean=2 ;;
	h) cat <<EOF
buildlib script options:
	-c: Clean up files.	
EOF
		exit ;;
	esac
done

cd include

if [ $clean -le 1 ] ; then
	tar zxvf readline-6.3.tar.gz
fi

cd readline-6.3

if [ $clean -ge 1 ] ; then
	make clean
	make uninstall
	cd ../
	rm -rf readline-6.3
else
	./configure --prefix=$PWD/../../ --with-curses
	make
	make install
	cd ../
fi

if [ $clean -le 1 ] ; then
	tar zxvf ncurses-5.9.tar.gz
fi

cd ncurses-5.9

if [ $clean -ge 1 ] ; then
	make clean
	make uninstall
	cd ../
	rm -rf ncurses-5.9
else
	./configure --prefix=$PWD/../../
	make
	make install
	cd ../
fi

if [ $clean -le 1 ] ; then
	tar zxvf libpng-1.6.23.tar.gz
fi

cd libpng-1.6.23

if [ $clean -ge 1 ] ; then
	make clean
	make uninstall
	cd ../
	rm -rf libpng-1.6.23
else
	./configure --prefix=$PWD/../../
	make
	make install
	cd ../
fi

