#!/bin/sh

dir=$1
id=$2
if [$# -ge 3]; then
	tstp=$3
else
	tstp=1
fi

if [$# -ge 4]; then
	filename=$4
else
	filename=${id##*/}
fi

files="$dir/*.sdf" 

#echo $files

mkdir $dir/$filename

for filepath in ${files}
do
	tmp=${filepath##*/}
	tmp=${tmp%.*}
	tmp="${tmp//[![:digit:]]/}"
	echo "processing ${filepath}"
	sdf2txt>$dir/$filename/$tmp.txt -cni -v $id $filepath
done
